- name: Áp bản vá bảo mật định kỳ
  hosts: droplets
  become: yes

  tasks:
    - name: Update package index
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Nâng cấp tất cả gói (bao gồm cả security)
      apt:
        upgrade: dist
        autoremove: yes
