#cloud-config
package_update: true
package_upgrade: true

users:
  - name: devops
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - ssh-rsa AAAA...your-public-key-here...

runcmd:
  - echo "User devops đã được tạo bởi cloud-init" > /var/log/cloud-init-user.log
